language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19


before_install:
  - yes | sdkmanager "platforms;android-28"

before_script:
- chmod +x gradlew

script:
    - ./gradlew assembleDebug