name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Android Emulator (faruktoptas)
      uses: faruktoptas/android-github-actions-emulator@latest
