name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Gradle Command
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: check

