name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build with Gradle
      uses: vgaidarji/android-github-actions/emulator@v1.0.0
