name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run UI Tests
      uses: ishubhamsinghtj/android-github-actions/emulator@v1.1.0
